services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: launchlane
      MYSQL_DATABASE: launchlane
      MYSQL_USER: launchlane
      MYSQL_PASSWORD: launchlane
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
